spring :
  application:
    name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/batch14_user_management
    username: postgres
    password: shas610

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        ddl: none
        ddl-auto: none
    show-sql: true
    generate-ddl: false
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      timeout: 10s
      connect-timeout: 10s
      database: 0
  cache:
    type: redis
    redis:
      time-to-live: 600s
      key-prefix: "cache:user-service:"
      cache-null-values: true
      use-key-prefix: true
server:
  port: 8001
  servlet:
    context-path: /user-service

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret-key: KOF9406KFOIE839EM#+]2L3\5=11J3OP)1

management:
  health:
    redis:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health